name       : pastebinit
version    : 1.6.2
release    : 1
source     :
    - https://github.com/pastebinit/pastebinit/archive/refs/tags/1.6.2.tar.gz : 81ab0ade7b58e3c48defcce3236ce3e97fbfadd02d55b205363756626f101915
license    : GPL-2.0-or-later
component  : system.utils
summary    : Lets you send anything you want directly to a pastebin from the command line
description: |
    This software lets you send a file or simply the result of a command directly to the pastebin you want (if it's supported) and gives you the URL in return.
rundeps    :
    - python-configparser
    - python-urllib3
build      : |
    pushd po
    %make
    popd
install    : |
    install -Dm0755 pastebinit $installdir/usr/bin/pastebinit

    install -dm0755 $installdir/usr/share/pastebin.d
    install -Dm0755 pastebin.d/* $installdir/usr/share/pastebin.d

    # Translations
    pushd po/mo
    for _lang in *; do
      install -Dm0644 ${_lang}/LC_MESSAGES/pastebinit.mo $installdir/usr/share/locale/${_lang}/LC_MESSAGES/pastebinit.mo
    done
    popd

    # Utils
    install -Dm0755 utils/pbput $installdir/usr/bin/pbput
    ln -s $installdir/usr/bin/pbput $installdir/usr/bin/pbputs
    ln -s $installdir/usr/bin/pbput $installdir/usr/bin/pbget

    # manpages
    install -Dm0644 utils/pbput.1 $installdir/usr/share/man/man1/pbput.1
    ln -s $installdir/usr/share/man/man1/pbput.1 $installdir/usr/share/man/man1/pbputs.1
    ln -s $installdir/usr/share/man/man1/pbput.1 $installdir/usr/share/man/man1/pbget.1
